---
alias: Outside Doorbell Notification
description: >-
  Send notifications when doorbell is pushed.

id: e91ddd71-0cd9-40d9-aee9-63ed93210013
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.outside_doorbell
    to: "on"

action:
  - service: notify.frenck_iphone
    data:
      title: Doorbell
      message: Ding dong! Someone is at the door!
  - service: notify.frenck_telegram
    data:
      message: Ding dong! Someone is at the door!
  - service: notify.daphne_iphone
    data:
      title: Deurbell
      message: Ding dong! Er staat iemand aan de deur!
  # The delay of 15 seconds with the single mode, acts as a cooldown
  # This prevent (childeren) to rappitly press the button, causing
  # a flood of notifications.
  - delay:
      seconds: 15
