---
alias: Office Lights Off
description: >-
  Turn lights off in my office when the alarm is armed.

id: 0a569417-918a-471c-a17f-803ab7add1e2
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm

condition:
  - condition: state
    entity_id: alarm_control_panel.house_alarm
    state:
      - armed_away
      - armed_home

action:
  - service: light.turn_off
    target:
      area_id: office
    data:
      transition: 5
