---
alias: Attic Ventilation
description: >-
  Controls the central ventilation system of the house.

  My central ventilation system is controlled by Sonoff Dual R2, running
  ESPHome. The ESPHome code can be found in the `esphome` folder, file:
  `attic_ventilation.yaml`.

  It handles two main cases:
    - The humidity of the bathroom.
    - Turn on ventilation when someone visits the restroom long enough to
      indicate it is a number 2 ;)

  Additionally, it:
    - Doesn't automatically interfere is the central ventilation is manually
      overridden.
    - Turns on the ventilation at high speed if shower use is detected
      (hot tap water is asked from the boiler).
    - When the house is in cleaning mode, ventilation is turned up to help
      when the floor is mopped.
    - Turns off the central ventilation when we go to sleep. We do want to
      be able to sleep in silence :)

id: "c2153826-fa86-4448-91a5-53791f86a5f5"
mode: queued
max_exceeded: silent
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.attic_variable_ventilation_manual_override
      - input_boolean.house_mode_cleaning
      - input_boolean.house_mode_sleep
      - input_number.bathroom_setting_humidity_high
      - input_number.bathroom_setting_humidity_low
      - sensor.bathroom_humidity

  - platform: state
    id: "ventilation"
    entity_id:
      - fan.attic_ventilation

  - platform: state
    entity_id: light.restroom
    to: "off"
    for:
      minutes: 10

  - platform: state
    entity_id: light.restroom
    to: "on"
    for:
      minutes: 3

  - platform: time
    id: "reset"
    at: input_datetime.house_setting_reset

action:
  - choose:
      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: time

        sequence:
          - &manual_override_off
            alias: "Reset manual override on attic ventilation"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.attic_variable_ventilation_manual_override

      - alias: "Activate cleaning mode"
        conditions:
          - alias: "When cleaning mode is on"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "on"

        sequence:
          - *manual_override_off
          - &high_speed
            alias: "Turn on ventilation on high speed"
            service: fan.turn_on
            target:
              entity_id: fan.attic_ventilation
            data:
              percentage: 100

      - alias: "Turn off when sleep mode is active and no hot tap water is used"
        conditions:
          - alias: "When the house is in sleep mode"
            condition: state
            entity_id: input_boolean.house_mode_sleep
            state: "on"

          - alias: "When hot tap water is not used"
            condition: not
            conditions:
              - &hot_tap_water_used
                alias: "When hot tap water is used"
                condition: state
                entity_id: binary_sensor.attic_boiler_hot_tap_water
                state: "on"

        sequence:
          - *manual_override_off
          - &turn_off
            alias: "Turn off the ventilation"
            service: fan.turn_off
            target:
              entity_id: fan.attic_ventilation

      - alias: "Ensure attic ventilation was not manually overriden"
        conditions:
          - alias: "When manually overriden"
            condition: state
            entity_id: input_boolean.attic_variable_ventilation_manual_override
            state: "on"

        # Do nothing, beyond this point, because of the manual override
        sequence: []

      - alias: "Manual attic ventilation override detected"
        conditions:
          - alias: "Attic ventilation has changed"
            condition: trigger
            id: "ventilation"

          - alias: "It was changed by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"

        sequence:
          - &manual_override_on
            alias: "Set attic ventilation as manually overriden"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.attic_variable_ventilation_manual_override

      - alias: "When the shower is used"
        conditions:
          - *hot_tap_water_used

        sequence:
          - *high_speed

      - alias: "Humidity in the bathroom is above the high threshold"
        conditions:
          - alias: "When the bathroom humidity is above the high threshold"
            condition: numeric_state
            entity_id: sensor.bathroom_humidity
            above: input_number.bathroom_setting_humidity_high

        sequence:
          - *high_speed

      - alias: "Humidity in the bathroom is above the low threshold"
        conditions:
          - alias: "When the bathroom humidity is above the low threshold"
            condition: numeric_state
            entity_id: sensor.bathroom_humidity
            above: input_number.bathroom_setting_humidity_low

        sequence:
          - &low_speed
            alias: "Turn on ventilation on low speed"
            service: fan.turn_on
            target:
              entity_id: fan.attic_ventilation
            data:
              percentage: 50

      - alias: "When there is a number 2 action in the restroom"
        conditions:
          - alias: "When the restoom lights are on for longer than 3 minutes"
            condition: state
            entity_id: light.restroom
            state: "on"
            for:
              minutes: 3

        sequence:
          - *low_speed

    default:
      - *turn_off
