---
alias: Living Room Climate Low
description: >-
  Turn down the heating in the living room.

  Gotta save the environment a bit, right? Also, the wallet likes it as well :)

id: cc6cad10-b5ee-4362-bd7b-2a67dde9e503
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
  - platform: time
    at: "22:00:00"

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state:
          - armed_away
          - armed_home
      - condition: time
        after: "22:00:00"

action:
  - service: climate.set_temperature
    target:
      area_id: living_room
    data:
      temperature: 15
