---
alias: Living Room Lights Off
description: >-
  Turn lights off in our living room.
  This is done based on the state of the alarm, or based on the luminosity
  outside.

id: d2cad90f-cc2f-43cd-aeea-b2450644e57d
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
      - input_boolean.living_room_automatic_lighting
      - sensor.garden_luminosity

condition:
  - condition: state
    entity_id:
      - light.living_room
    state: "on"
  - condition: or
    conditions:
      - condition: state
        entity_id:
          - alarm_control_panel.house_alarm
        state:
          - armed_away
          - armed_home
      - condition: and
        conditions:
          - condition: state
            entity_id:
              - input_boolean.living_room_automatic_lighting
            state: "on"
          - condition: numeric_state
            entity_id:
              - sensor.garden_luminosity
            above: 500.0

action:
  - service: light.turn_off
    target:
      area_id: living_room
    data:
      transition: 5
