---
alias: Living Room Vacuum
description: >-
  When the alarm gets arm away, we've left the home. In that case, run the
  vacuum cleaner if it has not ran the past 4 hours.

id: 80ce1910-b205-4374-89dc-d0444dfc637d
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm

condition:
  - condition: state
    entity_id: alarm_control_panel.house_alarm
    state: "armed_away"
  - condition: state
    entity_id: vacuum.living_room
    state: "docked"
    for:
      hours: 4

action:
  - service: vacuum.start
    target:
      entity_id: vacuum.living_room
  - service: vacuum.set_fan_speed
    target:
      entity_id: vacuum.living_room
    data:
      fan_speed: "Max"
