---
alias: Living Room Vacuum Fan Speed Reset
description: >-
  The vacuum cleaner remembers its last used fan speed.

  This is kinda annoying, as each time you start it... it might be a different
  setting (e.g., maybe last time we used a mop mode manually).

  Using this little automation, the fan speed is reset each time the vacuum
  docks for charging.

id: 5e172b51-dcbb-4cdf-8130-68c6ac3d245a
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: vacuum.living_room
    to: "docked"

condition:
  - condition: state
    entity_id: vacuum.living_room
    state: "docked"

action:
  - service: vacuum.set_fan_speed
    target:
      entity_id: vacuum.living_room
    data:
      fan_speed: "Standard"
