---
#
# https://www.home-assistant.io/integrations/default_config
#
#default_config:

automation:

#cloud:

config:

frontend:

map:

person:

script:

sun:

system_health:

ios:

mobile_app:

#history:
#logbook:
#ssdp:
#updater:
#zeroconf:
