---
alias: "House Cleaning Mode"
description: >-
  Automation that reacts to our house cleaning mode switch.

  This switch activates the cleaning mode in our home.

id: "4c3e3dcf-bfd7-419a-aee2-fac076dd1d72"
mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: sensor.house_cleaning_mode_button
    to: "on"

action:
  - choose:
      - alias: "Turn on cleaning mode when its off"
        conditions:
          - alias: "When cleaning mode is off"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "off"

        sequence:
          - alias: "Turn on cleaning mode"
            service: input_boolean.turn_on
            target: &target
              entity_id: input_boolean.house_mode_cleaning

          - alias: "Annouce cleaning mode turned on"
            service: tts.cloud_say
            entity_id: media_player.office_speaker
            data:
              message: "Schoonmaak modus geactiveerd"

      - alias: "Turn off cleaning mode when its on"
        conditions:
          - alias: "When cleaning mode is on"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "on"

        sequence:
          - alias: "Turn off cleaning mode"
            service: input_boolean.turn_off
            target: *target

          - alias: "Annouce cleaning mode turned off"
            service: tts.cloud_say
            entity_id: media_player.office_speaker
            data:
              message: "Schoonmaak modus uitgeschakeld"
