---
alias: "Hall Lights"
description: >-
  Controls the hall lights.

  They mainly respond on motion; but also when the alarm arms.

id: "dae7c422-03ff-4ae6-a06d-65e4907872c1"
mode: queued
max_exceeded: silent
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded
      - scene_reloaded

  - platform: state
    entity_id:
      - input_boolean.hall_variable_lights_manual_override
      - input_boolean.house_mode_away
      - input_boolean.house_mode_cleaning
      - input_boolean.house_mode_eco
      - input_boolean.house_mode_sleep
      - input_boolean.house_mode_guest
      - sensor.hall_luminosity
      - sensor.outside_luminosity

  - platform: state
    id: "lights"
    entity_id:
      - light.hall_ceiling

  - platform: state
    id: "motion"
    entity_id: binary_sensor.hall_motion
    from: "off"
    to: "on"

  - platform: state
    id: "clear"
    entity_id: binary_sensor.hall_motion
    from: "on"
    to: "off"
    for:
      seconds: 15

  - platform: time
    id: "reset"
    at: input_datetime.house_setting_reset

action:
  - choose:
      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: time

        sequence:
          - &manual_override_off
            alias: "Reset manual override on hall lights"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.hall_variable_lights_manual_override

      - alias: "Activate cleaning mode"
        conditions:
          - alias: "When cleaning mode is on"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "on"

        sequence:
          - *manual_override_off
          - alias: "Activate hall cleaning scene"
            service: scene.turn_on
            target:
              entity_id: scene.hall_cleaning
            data: &transition
              transition: 2.5

      - alias: "Turn off when sleep or away mode is active"
        conditions:
          - condition: or
            conditions:
              - alias: "When the house is in away mode"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"

              - alias: "When the house is in sleep mode"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"

        sequence:
          - *manual_override_off
          - &turn_off
            alias: "Turn off all the hall lights"
            service: light.turn_off
            target:
              area_id: hall
            data:
              transition: 5

      - alias: "Ensure hall light are not manually overriden"
        conditions:
          - alias: "When manually overriden"
            condition: state
            entity_id: input_boolean.hall_variable_lights_manual_override
            state: "on"

        # Do nothing, beyond this point, because of the manual override
        sequence: []

      - alias: "Manual hall lights override detected"
        conditions:
          - alias: "One of the lights has changed"
            condition: trigger
            id: "lights"

          - alias: "It was changed by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"

        sequence:
          - alias: "Set hall lights as manually overriden"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.hall_variable_lights_manual_override

      - alias: "Activate scene when motion is detected"
        conditions:
          - condition: or
            conditions:
              - alias: "When motion detector is on"
                condition: state
                entity_id: binary_sensor.hall_motion
                state: "on"

              - alias: "When motion detector isn't off for more than 1 min"
                condition: not
                conditions:
                  - alias: "When motion dector is off for more than 1 min"
                    condition: state
                    entity_id: binary_sensor.hall_motion
                    state: "off"
                    for:
                      seconds: 15

          - &condition_low_light
            alias: "When light conditions are low"
            condition: or
            conditions:
              - alias: "When light from outside is low"
                condition: numeric_state
                entity_id: sensor.outside_luminosity
                below: 500
              - alias: "When light condition in the hall are low"
                condition: numeric_state
                entity_id: sensor.hall_luminosity
                below: 50

        sequence:
          - &scene_select
            choose:
              - alias: "Activate hall sleep scene when in sleep mode"
                conditions:
                  - alias: "When house is in sleep mode"
                    condition: state
                    entity_id: input_boolean.house_mode_sleep
                    state: "on"
                sequence:
                  - alias: "Activate hall sleep scene"
                    service: scene.turn_on
                    target:
                      entity_id: scene.hall_sleep
                    data: *transition

              - alias: "Activate hall night scene when it's pitch-dark outside"
                conditions:
                  - alias: "When it is pitch-dark outside"
                    condition: numeric_state
                    entity_id: sensor.outside_luminosity
                    below: 100
                sequence:
                  - alias: "Activate hall night scene"
                    service: scene.turn_on
                    target:
                      entity_id: scene.hall_night
                    data: *transition

              - alias: "Activate hall sunrise/sunset scene otherwise"
                conditions:
                  - *condition_low_light
                sequence:
                  - choose:
                      - alias: "Activate sunrise scene until the late aternoon"
                        conditions:
                          - condition: time
                            before: "15:00:00"
                        sequence:
                          - alias: "Activate hall sunrise scene"
                            service: scene.turn_on
                            target:
                              entity_id: scene.hall_sunrise
                            data: *transition
                    default:
                      - alias: "Activate hall sunset scene"
                        service: scene.turn_on
                        target:
                          entity_id: scene.hall_sunset
                        data: *transition

      - alias: "When guest mode is active, keep lights on"
        conditions:
          - alias: "When house is in guest mode"
            condition: state
            entity_id: input_boolean.house_mode_guest
            state: "on"
        sequence:
          - *scene_select

      - alias: "When house not in eco mode, keep lights on"
        conditions:
          - alias: "When house is not in "
            condition: state
            entity_id: input_boolean.house_mode_eco
            state: "off"
        sequence:
          - *scene_select

    default:
      - *turn_off
