---
blueprint:
  name: Zigbee2MQTT - Philips Hue Dimmer Remote Simple Light Control
  description: |
    A simple Hue Remote blueprint to control lights.

    The "on" button, turns on the lights to the last set brightness (unless
    the force brightness is toggled on in the blueprint). Holding the "on"
    button for a second, turns up the light to a 100% brightness instantly.

    Dim up/down buttons will change the brightness smoothly and can be pressed
    and hold until the brightness is satisfactory.

    Finally, the off button, turns the light off.

  domain: automation
  input:
    remote:
      name: Remote
      description: Philips Hue Remote to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light
    force_brightness:
      name: Force turn on brightness
      description: >
        Force the brightness to the set level below, when the "on" button on
        the remote is pushed
      default: false
      selector:
        boolean:
    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 50
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
          unit_of_measurement: "%"

mode: queued
max_exceeded: silent

variables:
  force_brightness: !input force_brightness
  action: "{{ trigger.to_state.state }}"

trigger:
  - platform: state
    entity_id: !input remote
    to:
      - "down-hold"
      - "down-press"
      - "off-press"
      - "on-hold"
      - "on-press"
      - "up-hold"
      - "up-press"

action:
  - choose:
      - conditions:
          - "{{ action == 'on-press' }}"
          - "{{ force_brightness }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              transition: 1
              brightness_pct: !input brightness
      - conditions: "{{ action == 'on-press' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              transition: 1
      - conditions: "{{ action== 'on-hold' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_pct: 100
      - conditions: "{{ action == 'up-press' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step_pct: 20
              transition: 1
      - conditions: "{{ action == 'up-hold' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step_pct: 10
              transition: 1
      - conditions: "{{ action == 'down-press' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step_pct: -20
              transition: 1
      - conditions: "{{ action == 'down-hold' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step_pct: -10
              transition: 1
      - conditions: "{{ action == 'off-press' }}"
        sequence:
          - service: light.turn_off
            target: !input light
            data:
              transition: 1
