---
alias: "Kitchen Water Heater"
description: >-
  This automation tries to save energy usage on the water heater in
  our kitchen. Its a little water heater/boiler unit that keeps around
  15 liters of water at 80 degrees celcius.

  Eventhough heating it up in the morning again costs a lot of energy as well,
  it does lower the temperature difference between inside/outside the boiler
  causing less energy to be lost from that. In the morning we have solar
  power to help us out with heating it up again.

id: "a0d305d2-38fa-4f13-9a94-820e252c1a5a"
mode: single
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.house_mode_away
      - input_boolean.house_mode_cleaning
      - input_boolean.house_mode_sleep
      - input_boolean.house_mode_vacation

  - platform: state
    entity_id:
      - switch.kitchen_water_heater
    from:
      - "unavailable"
      - "unknown"

condition:
  - alias: "Ensure the water heater is available"
    condition: not
    conditions:
      - condition: state
        entity_id: switch.kitchen_water_heater
        state: "unavailable"

action:
  - alias: "Decide if the water heater should be on or off"
    choose:
      - alias: "Turn off the water heater"
        conditions:
          - alias: "When cleaning mode is off"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "off"

          - alias: "When any of the following is true"
            condition: or
            conditions:
              - alias: "When the house is in away mode"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"

              - alias: "When the house is in sleep mode"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"

              - alias: "When the house is in vacation mode"
                condition: state
                entity_id: input_boolean.house_mode_vacation
                state: "on"

        sequence:
          - alias: "Turn off the water heater"
            service: switch.turn_off
            target: &target
              entity_id: switch.kitchen_water_heater

    default:
      - alias: "Turn on the water heater"
        service: switch.turn_on
        target: *target
