#
# Our home brewed automations, that are too complex for normal automate scripting
#
jan_automation:
  optimizer:
    home_load_sensor: "casa_consumo_total"
    load: 100
    switch: "optimizer"
    power_meter_sensor: "sensor.power_meter"
    producer_sensor: "sensor.production"
    consumers:
      - switch: "switch.onvis_s3eu_519a30"
        load: 2200
      - switch: "switch.onvis_s3eu_51c26c"
        load: 1000
